name: ${project.name}
version: ${project.version}
main: com.xaltar.redstoneguard.XaltarRedstoneGuard
api-version: '1.21'
folia-supported: true
author: RitchiQc
description: ${project.description}

commands:
  xalguard:
    description: Commandes principales de XaltarRedstoneGuard
    usage: /xalguard <limit|reload>
    aliases: [xrg]

permissions:
  xalguard.limit:
    description: Permet d'afficher les limites du chunk actuel
    default: true
  xalguard.reload:
    description: Permet de recharger la configuration du plugin
    default: op
